### ISSUE TITLE
[Job Post]: Codebase steward for quality

### ISSUE THREAD

**Issue by MirjamvT** [t9tio/open-source-jobs#14]
- Job title: Codebase steward for quality
- Job link: https://about.publiccode.net/roles/quality.html
- Organization: Foundation for Public Code
- Organization GitHub URL: https://github.com/publiccodenet
- Locations of the job: Amsterdam
- Tech keywords of the job: quality assurance

**Comment by timqian** [comment]
@MirjamvT Thanks for posting the job and `The Foundation for Public Code` looks cool. Do you have your own projects or your mission is only about helping other projects?

I am considering to add your foundation to [open companies](https://oo.t9t.io/organizations) too

**Comment by MirjamvT** [comment]
thanks, i've just created a company page:
https://github.com/t9tio/open-source-jobs/issues/15 Is this what you need
to create an open company page?

We work with codebases of public organizations. We steward these codebases,
increasing their quality and use. we don't build new ones ourselves.

Best regards,
Mirjam van Tiel
+31 6 4662 8454

**Comment by bvhme** [comment]
@timqian, we're basically trying to bridge the gap to open source for public organisations like governments by creating an open source foundation that speaks their language and caters to their needs. Very much needed. We're an organization controlled by our members who are public entities.

**Comment by timqian** [comment]
@MirjamvT @bvhme Thanks this job has been added https://oo.t9t.io/jobs
