### ISSUE TITLE
[Org Post]:Foundation for Public Code

### ISSUE THREAD

**Issue by MirjamvT** [t9tio/open-source-jobs#15]
- Name: Foundation for Public Code
- GitHub URL: https://github.com/publiccodenet
- Official URL: https://publiccode.net/
- Job URL: https://about.publiccode.net/roles/
- One sentence intro: We help open source projects for public organizations (like cities) become successful, build sustainable communities around them and create a thriving public open source ecosystem.
- majorRepos: https://github.com/publiccodenet/about, https://github.com/publiccodenet/standard
- email: info@publiccode.net

**Comment by timqian** [comment]
thanks, the org has been added
https://oo.t9t.io/organization/Foundation%20for%20Public%20Code

I used your description on github as it is shorter and looks better on different devices

**Comment by MirjamvT** [comment]
thanks!
